# Generated by Django 2.2.3 on 2019-07-23 14:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_x', models.IntegerField()),
                ('size_y', models.IntegerField()),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
