# Generated by Django 2.2.3 on 2019-07-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HexCanvas',
            fields=[
                ('canvas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='canvas.Canvas')),
            ],
            bases=('canvas.canvas',),
        ),
    ]
