# Generated by Django 2.2.4 on 2019-08-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvas',
            name='content',
            field=models.TextField(),
        ),
    ]
